.\" Manpage for enkode.
.\" Contact by.cmsc@gmail.com to correct errors or typos.
.TH enkode 1 "23 January 2019" "5.0.1" "Executable bash script"
.SH NAME
.B enkode
\- generate an analytical data score from a sound file.
.SH SYNOPSIS
.B enkode
[OPTION(S)[ \fIvalue\fR|=\fIvalue\fR]] sound_file
.SH DESCRIPTION
.B enkode
interprets a sound file in terms of numeric score devoted to the analysis or music synthesis. This script has been designed more specifically for undetermined pitch percussive music.
.RE
The audio formats recognised are listed on the praat manual.
.SH OPTIONS
.TP
The three following options take as argument a number or a list of five numbers allowing to set the recursive discrimination as coefficient.
.RE
Then the number of classes is function of the coefficient of recursivity (coeff) according to a positive number as:
.RS
.RS
integer = - 1 + 2^coeff;
.RE
.RS
float = 2^(floor coeff).
.RE
.RE
.TP
.BR \-I " " \fInum/list\fR ", " \-\-as\-int=\fInum/list\fR " "
Interpret the analysis in term of class number according to the discrimination as argument.
.RE
.TP
.BR \-T " " \fInum/list\fR ", " \-\-as\-tc=\fInum/list\fR " "
Convert the previous result to thrifty code.
.RE
.TP
.BR \-G " " \fInum/list\fR ", " \-\-as\-gc=\fInum/list\fR " "
Convert the previous result to gray code.
.RE
.TP
The options with + prepended allow to save the data files in the ~/Documents/enkode/<sampleName>/ directory:
.RS
.BR +profile
.RE
.RS
.BR +textgrid
.RE
.RS
.BR \-textgrid=\fIpath\fR " "
.RS
Allow to use your own textgrid.
.RE
.RS
The segmentation has to be on the first tier of the textgrid and named as ordered integers from 1 until the total number of events.
.RE
.RE
.RS
.BR +spectrum
.RE
.RS
.BR \-spectrum=\fIfreq/bin\fR " " 
.RS
Allow to get the spectrum analysis on the stdout.
.RE
.RS
Each line represents the spectrum dataset as re(Pa/Hz) usualy on 116 bins as the bin value and from 0 to 5000 Hz as the freq value (values by default with the option +spectrum) for each event defined by the textgrid.
.RE
.RE
.RS
.BR \-p ", " \-\-par
.RS
Allow to display some preliminary values for the segmentation in order to adjust some parameters if needed. 
.RE
.RS
Note that the files +textgrid and +profile are automatically saved in the ~/Documents/enkode/<sampleName>/ directory.
.RE
.RE
.TP
.BR \-\-loudness\-diff\-thres=\fInumber\fR " " 
Set the value of loudness in sone units between two potential events to validate discrimination. 
.RE
.RS
The default value is the mean value of the variations peak/valley and valley/peak.
.RE
.TP
.BR \-\-loudness\-min\-thres =\fInumber\fR " " 
Set the minimal value of loudness applied to peaks in sone units to validate a potential event. 
.RE
.RS
The default value is the minimum value of a peak after the \-\-loudness\-diff\-thres filtering.
.RE
.TP
.BR \-\-loudness\-max\-thres =\fInumber\fR " " 
Set the maximal value of loudness applied to valleys in sone units to validate a potential event. 
.RE
.RS
The default value is the maximum value of a valley after the \-\-loudness\-min\-thres filtering.
.RE
.TP
Note that the default value of the following options is inside curly bracket.
.TP
.BR \-\-cutoff\-frequency =\fInumber\fR " " {100}
Set the cut off frequency of the low pass filter for bass discrimination.
.TP
.BR \-\-smooth\-frequency =\fInumber\fR " " {500}
Set the bandwidth frequency for cepstral smoothing.
.SH DEPENDENCIES
.BR praat " - " 
http://www.fon.hum.uva.nl/praat/
.RE
.BR sbcl "  - "
http://www.sbcl.org/
.SH BUGS
In case of failure an error.log file is generated.
.RE
Please report any issue at the author.
.SH AUTHOR
Yann Ics
.RE
by.cmsc@gmail.com
.SH SEE ALSO
It exists a full documentation in a form of LaTeX book to describe the executable
.B enkode
with its parameters and its developments on:
.RE
https://www.overleaf.com/read/sjhfhthgkgdj
