.\" Manpage for enkode.
.\" Contact by.cmsc@gmail.com to correct errors or typos.
.TH enkode 1 "16 October 2019" "6.0.1 alpha" "Executable bash script"
.SH NAME
.B enkode
\- generate an analytical data score from a sound file.
.SH SYNOPSIS
.B enkode
[OPTION(S)[ \fIvalue\fR|=\fIvalue\fR]] sound_file
.SH DESCRIPTION
The command line
.B enkode
interprets a sound file in terms of numeric score devoted to the analysis or music synthesis. This script has been designed more specifically for undetermined pitch percussive music.
.RS
.RE
Thus,
.B enkode
displays a sequence of events which are defined for each line by the duration of the event, the value of the first partial as f0, the centroid, the loudness and the low pass filtered event loudness.
.RS
.RE
The audio formats recognised are listed on the
.B praat
manual.
.SH OPTIONS
.TP
The three following options take as argument a number or a list of five numbers allowing to set the recursive discrimination as coefficient.
.RE
Then the number of classes is function of the coefficient of recursivity (coeff) according to a positive number as:
.RS
.RS
integer = - 1 + 2^coeff;
.RE
.RS
float = 2^(floor coeff).
.RE
.RE
.TP
.BR \-I " " \fInum\fR|\fIlist\fR ", " \-\-as\-int =\fInum\fR|\fIlist\fR " "
Interpret the analysis in term of class number according to the discrimination as argument.
.RE
.TP
.BR \-G " " \fInum\fR|\fIlist\fR ", " \-\-as\-gc =\fInum\fR|\fIlist\fR " "
Convert the previous result to gray code.
.RE
.TP
.BR \-T " " \fInum\fR|\fIlist\fR ", " \-\-as\-tc =\fInu\fR|\fIlist\fR " "
Convert the previous result to thrifty code.
.RE
.TP
Setting parameters:
.RE
.TP
.BR \-\-loudness\-diff\-thres =\fInumber\fR " "
Set the value of loudness in sone units between two potential events to validate discrimination.
.RE
.RS
The default value is the mean value of the variations peak/valley and valley/peak.
.RE
.TP
.BR \-\-loudness\-min\-thres =\fInumber\fR " "
Set the minimal value of loudness applied to peaks in sone units to validate a potential event.
.RE
.RS
The default value is the minimum value of a peak after the \-\-loudness\-diff\-thres filtering.
.RE
.TP
.BR \-\-loudness\-max\-thres =\fInumber\fR " "
Set the maximal value of loudness applied to valleys in sone units to validate a potential event.
.RE
.RS
The default value is the maximum value of a valley after the \-\-loudness\-min\-thres filtering.
.RE
.TP
Note that the default value of the following options is inside curly bracket.
.TP
.BR \-\-cutoff\-frequency =\fInumber\fR " " {100}
Set the cut off frequency of the low pass filter for bass discrimination.
.TP
.BR \-\-smooth\-frequency =\fInumber\fR " " {500}
Set the bandwidth frequency for cepstral smoothing.
.RE
.TP
Additional options:
.RE
.TP
.BR \-o " " \fIpath\fR|\fItrue\fR ", " \-\-outdir =\fIpath\fR|\fItrue\fR " "
Write output in OUTDIR. If the argument is set to TRUE, then OUTDIR = '~/Documents/enkode/<sampleName>/'.
.RE
.TP
.BR \-p ", " \-\-par
Allow to display some preliminary values for the segmentation in order to adjust some parameters if needed.
.RE
.TP
.BR \-\-spectrum
Allow to get the spectrum analysis on the stdout.
.RE
.RS
Each line represents the spectrum dataset as re(Pa/Hz) on 116 bins from 0 to 5000 Hz for each event defined by the textgrid.
.RE
.TP
.BR \-\-textgrid =\fIpath\fR " "
Allow to use your own textgrid.
.RE
.RS
The segmentation has to be on the first tier of the textgrid and named as ordered integers from 1 until the total number of events.
.SH DEPENDENCIES
.BR praat " - "
http://www.fon.hum.uva.nl/praat/
.RE
.BR sbcl "  - "
http://www.sbcl.org/
.SH BUGS
In case of failure an error.log file is generated.
.RE
Please report any issue at the author.
.SH AUTHOR
Yann Ics
.RE
by.cmsc@gmail.com
.SH SEE ALSO
It exists a full documentation in a form of LaTeX book to describe the executable
.B enkode
with its parameters and its developments on:
.RE
https://www.overleaf.com/read/sjhfhthgkgdj
